In [1]:
import pandas as pd
import numpy as np

In [2]:
DATA_PATH = "../data/raw/data.csv"

df = pd.read_csv(DATA_PATH)

df.head()

C:\Users\yagne\AppData\Local\Temp\ipykernel_15008\701571264.py:3: DtypeWarning: Columns (3: artists, 8: id, 14: name, 16: release_date) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DATA_PATH)

,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo
0,0.0594,1921.0,0.982,"['Sergei Rachmaninoff', 'James Levine', 'Berli...",0.279,831667.0,0.211,0.0,4BJqT0PrAfrxzMOxytFOIz,0.878000,10.0,0.665,-20.096,1.0,"Piano Concerto No. 3 in D Minor, Op. 30: III. ...",4.0,1921,0.0366,80.954
1,0.9630,1921.0,0.732,['Dennis Day'],0.819,180533.0,0.341,0.0,7xPhfUan2yNtyFG0cUWkt8,0.000000,7.0,0.160,-12.441,1.0,Clancy Lowered the Boom,5.0,1921,0.4150,60.936
2,0.0394,1921.0,0.961,['KHP Kridhamardawa Karaton Ngayogyakarta Hadi...,0.328,500062.0,0.166,0.0,1o6I8BglA6ylDMrIELygv1,0.913000,3.0,0.101,-14.850,1.0,Gati Bali,5.0,1921,0.0339,110.339
3,0.1650,1921.0,0.967,['Frank Parker'],0.275,210000.0,0.309,0.0,3ftBPsC5vPBKxYSee08FDH,0.000028,5.0,0.381,-9.316,1.0,Danny Boy,3.0,1921,0.0354,100.109
4,0.2530,1921.0,0.957,['Phil Regan'],0.418,166693.0,0.193,0.0,4d6HGyGT8e121BsdKmw9v6,0.000002,3.0,0.229,-10.096,1.0,When Irish Eyes Are Smiling,2.0,1921,0.0380,101.665

In [3]:
df.shape

(170653, 19)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 170653 entries, 0 to 170652
Data columns (total 19 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   valence           157490 non-null  float64
 1   year              157490 non-null  float64
 2   acousticness      157490 non-null  float64
 3   artists           157490 non-null  str
 4   danceability      157490 non-null  float64
 5   duration_ms       157490 non-null  float64
 6   energy            157490 non-null  float64
 7   explicit          157490 non-null  float64
 8   id                157490 non-null  str
 9   instrumentalness  157490 non-null  float64
 10  key               157490 non-null  float64
 11  liveness          157490 non-null  float64
 12  loudness          157490 non-null  float64
 13  mode              157490 non-null  float64
 14  name              157490 non-null  str
 15  popularity        157490 non-null  float64
 16  release_date      157490 non-null  str
 17  speechiness       157490 non-null  float64
 18  tempo             157490 non-null  float64
dtypes: float64(15), str(4)
memory usage: 24.7 MB

In [5]:
df.describe(include = 'all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
valence,157490.0,NaN,NaN,NaN,0.528954,0.263286,0.0,0.317,0.54,0.748,1.0
year,157490.0,NaN,NaN,NaN,1975.906204,26.210815,1921.0,1954.0,1976.0,1998.0,2020.0
acousticness,157490.0,NaN,NaN,NaN,0.509352,0.377327,0.0,0.106,0.532,0.903,0.996
artists,157490,32006,['Эрнест Хемингуэй'],1211,NaN,NaN,NaN,NaN,NaN,NaN,NaN
danceability,157490.0,NaN,NaN,NaN,0.537658,0.176132,0.0,0.415,0.548,0.669,0.988
duration_ms,157490.0,NaN,NaN,NaN,230226.697873,124674.233397,5108.0,169533.0,206587.0,261573.0,5403500.0
energy,157490.0,NaN,NaN,NaN,0.477625,0.267541,0.0,0.25,0.463,0.698,1.0
explicit,157490.0,NaN,NaN,NaN,0.085072,0.27899,0.0,0.0,0.0,0.0,1.0
id,157490,157490,4BJqT0PrAfrxzMOxytFOIz,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
instrumentalness,157490.0,NaN,NaN,NaN,0.169714,0.315752,0.0,0.0,0.000227,0.11,1.0
key,157490.0,NaN,NaN,NaN,5.204197,3.513555,0.0,2.0,5.0,8.0,11.0
liveness,157490.0,NaN,NaN,NaN,0.205484,0.173417,0.0,0.099,0.136,0.261,0.999
loudness,157490.0,NaN,NaN,NaN,-11.533284,5.711133,-60.0,-14.716,-10.648,-7.225,3.855
mode,157490.0,NaN,NaN,NaN,0.706775,0.455242,0.0,0.0,1.0,1.0,1.0
name,157490,124353,White Christmas,71,NaN,NaN,NaN,NaN,NaN,NaN,NaN
popularity,157490.0,NaN,NaN,NaN,31.415068,22.270043,0.0,9.0,34.0,49.0,100.0
release_date,157490,10777,1945,1446,NaN,NaN,NaN,NaN,NaN,NaN,NaN
speechiness,157490.0,NaN,NaN,NaN,0.100117,0.166722,0.0,0.035,0.0451,0.076175,0.97
tempo,157490.0,NaN,NaN,NaN,116.712327,30.73461,0.0,93.21825,114.579,135.35475,243.507

In [6]:
df.isna()

,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170648,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
170649,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
170650,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
170651,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
170652,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

In [7]:
df.isna().sum()

valence             13163
year                13163
acousticness        13163
artists             13163
danceability        13163
duration_ms         13163
energy              13163
explicit            13163
id                  13163
instrumentalness    13163
key                 13163
liveness            13163
loudness            13163
mode                13163
name                13163
popularity          13163
release_date        13163
speechiness         13163
tempo               13163
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(13162)

In [9]:
# List of audio features.
features = [
    "acousticness",
    "danceability",
    "energy",
    "instrumentalness",
    "liveness",
    "loudness",
    "speechiness",
    "valence",
    "tempo",
    "duration_ms",
    "key"
]

In [10]:
df[features].info()

<class 'pandas.DataFrame'>
RangeIndex: 170653 entries, 0 to 170652
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   acousticness      157490 non-null  float64
 1   danceability      157490 non-null  float64
 2   energy            157490 non-null  float64
 3   instrumentalness  157490 non-null  float64
 4   liveness          157490 non-null  float64
 5   loudness          157490 non-null  float64
 6   speechiness       157490 non-null  float64
 7   valence           157490 non-null  float64
 8   tempo             157490 non-null  float64
 9   duration_ms       157490 non-null  float64
 10  key               157490 non-null  float64
dtypes: float64(11)
memory usage: 14.3 MB

In [11]:
df[features].describe().T

,count,mean,std,min,25%,50%,75%,max
acousticness,157490.0,0.509352,0.377327,0.0,0.10600,0.532000,0.903000,0.996
danceability,157490.0,0.537658,0.176132,0.0,0.41500,0.548000,0.669000,0.988
energy,157490.0,0.477625,0.267541,0.0,0.25000,0.463000,0.698000,1.000
instrumentalness,157490.0,0.169714,0.315752,0.0,0.00000,0.000227,0.110000,1.000
liveness,157490.0,0.205484,0.173417,0.0,0.09900,0.136000,0.261000,0.999
loudness,157490.0,-11.533284,5.711133,-60.0,-14.71600,-10.648000,-7.225000,3.855
speechiness,157490.0,0.100117,0.166722,0.0,0.03500,0.045100,0.076175,0.970
valence,157490.0,0.528954,0.263286,0.0,0.31700,0.540000,0.748000,1.000
tempo,157490.0,116.712327,30.734610,0.0,93.21825,114.579000,135.354750,243.507
duration_ms,157490.0,230226.697873,124674.233397,5108.0,169533.00000,206587.000000,261573.000000,5403500.000
key,157490.0,5.204197,3.513555,0.0,2.00000,5.000000,8.000000,11.000

In [12]:
df[features].isna()

,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,valence,tempo,duration_ms,key
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
170648,True,True,True,True,True,True,True,True,True,True,True
170649,True,True,True,True,True,True,True,True,True,True,True
170650,True,True,True,True,True,True,True,True,True,True,True
170651,True,True,True,True,True,True,True,True,True,True,True
170652,True,True,True,True,True,True,True,True,True,True,True

In [13]:
df[features].isna().sum()

acousticness        13163
danceability        13163
energy              13163
instrumentalness    13163
liveness            13163
loudness            13163
speechiness         13163
valence             13163
tempo               13163
duration_ms         13163
key                 13163
dtype: int64

In [14]:
df[features].corr()

,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,valence,tempo,duration_ms,key
acousticness,1.000000,-0.270214,-0.749121,0.334477,-0.020999,-0.559436,-0.045483,-0.182371,-0.207239,-0.077758,-0.020424
danceability,-0.270214,1.000000,0.223967,-0.278042,-0.098623,0.284495,0.239599,0.559819,0.006267,-0.143377,0.024673
energy,-0.749121,0.223967,1.000000,-0.283362,0.121522,0.783078,-0.079981,0.354036,0.251567,0.043842,0.027217
instrumentalness,0.334477,-0.278042,-0.283362,1.000000,-0.046892,-0.408178,-0.123753,-0.195146,-0.105878,0.085503,-0.014567
liveness,-0.020999,-0.098623,0.121522,-0.046892,1.000000,0.054037,0.133409,0.004437,0.005771,0.041613,0.000116
loudness,-0.559436,0.284495,0.783078,-0.408178,0.054037,1.000000,-0.149560,0.314644,0.209811,0.000121,0.016278
speechiness,-0.045483,0.239599,-0.079981,-0.123753,0.133409,-0.149560,1.000000,0.046713,-0.012305,-0.088703,0.023733
valence,-0.182371,0.559819,0.354036,-0.195146,0.004437,0.314644,0.046713,1.000000,0.174216,-0.196635,0.030009
tempo,-0.207239,0.006267,0.251567,-0.105878,0.005771,0.209811,-0.012305,0.174216,1.000000,-0.026349,0.002221
duration_ms,-0.077758,-0.143377,0.043842,0.085503,0.041613,0.000121,-0.088703,-0.196635,-0.026349,1.000000,-0.005567
key,-0.020424,0.024673,0.027217,-0.014567,0.000116,0.016278,0.023733,0.030009,0.002221,-0.005567,1.000000

In [15]:
df.tail(13163).isna().sum()

valence             13163
year                13163
acousticness        13163
artists             13163
danceability        13163
duration_ms         13163
energy              13163
explicit            13163
id                  13163
instrumentalness    13163
key                 13163
liveness            13163
loudness            13163
mode                13163
name                13163
popularity          13163
release_date        13163
speechiness         13163
tempo               13163
dtype: int64

In [16]:
df[['name', 'artists']].head(10)

,name,artists
0,"Piano Concerto No. 3 in D Minor, Op. 30: III. ...","['Sergei Rachmaninoff', 'James Levine', 'Berli..."
1,Clancy Lowered the Boom,['Dennis Day']
2,Gati Bali,['KHP Kridhamardawa Karaton Ngayogyakarta Hadi...
3,Danny Boy,['Frank Parker']
4,When Irish Eyes Are Smiling,['Phil Regan']
5,Gati Mardika,['KHP Kridhamardawa Karaton Ngayogyakarta Hadi...
6,The Wearing of the Green,['John McCormack']
7,"Morceaux de fantaisie, Op. 3: No. 2, Prélude i...",['Sergei Rachmaninoff']
8,La Mañanita - Remasterizado,['Ignacio Corsini']
9,Il Etait Syndiqué,['Fortugé']

In [17]:
df['name'].nunique()

124353

In [18]:
df['name'].value_counts()

name
White Christmas                                               71
Winter Wonderland                                             58
Summertime                                                    49
Jingle Bells                                                  47
Overture                                                      44
                                                              ..
Tchaikovsky: Serenade in C Major, Op. 48: II. Valse            1
Prem Shudhu Mor                                                1
Abend, ein kleines reinliches Zimmer - Teil 05                 1
Lucia di Lamermoor: Act II: Scene 2: Se tradirmi tu potrai     1
Frauenliebe und Leben, Op. 42: VII. An meinem Herzen           1
Name: count, Length: 124353, dtype: int64

In [19]:
len(df['name'].value_counts()[df['name'].value_counts() > 1])

17506

In [20]:
df[df['name'] == 'White Christmas'].head()

,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo
2842,0.0486,1936.0,0.995,['Harry James'],0.211,197360.0,0.0653,0.0,6K8aoScBFtdQjqCQqA1LDY,0.875000,2.0,0.107,-24.009,1.0,White Christmas,14.0,1936,0.0414,133.594
4006,0.2470,1942.0,0.673,"['Bing Crosby', 'Ken Darby Singers', 'John Sco...",0.317,177480.0,0.1580,0.0,4so0Wek9Ig1p6CRCHuINwW,0.353000,9.0,0.338,-16.485,1.0,White Christmas,76.0,01-01-1942,0.0381,130.503
4527,0.2250,1944.0,0.905,['The Meltones'],0.409,193373.0,0.2630,0.0,7E0KaPMjaU0f6MgH8DKeMh,0.000647,5.0,0.272,-10.080,1.0,White Christmas,6.0,14-06-1944,0.0258,84.126
4619,0.1860,1945.0,0.907,"['Bing Crosby', 'Ken Darby Singers', 'John Sco...",0.226,183613.0,0.2020,0.0,3XsaSIPWvM61RIFfeb0BBR,0.000056,9.0,0.387,-16.222,1.0,White Christmas,49.0,01-01-1945,0.0333,94.208
4626,0.1940,1945.0,0.970,['Frank Sinatra'],0.229,195493.0,0.0911,0.0,6zTodEJxZNaHIsfK976gSM,0.000270,11.0,0.389,-18.707,1.0,White Christmas,39.0,1945,0.0332,86.280

In [21]:
df['artists'].nunique()

32006

In [22]:
df['artists'].value_counts()

artists
['Эрнест Хемингуэй']                                                                                                   1211
['Эрих Мария Ремарк']                                                                                                  1068
['Francisco Canaro']                                                                                                    942
['Ignacio Corsini']                                                                                                     628
['Frank Sinatra']                                                                                                       603
                                                                                                                       ...
['Marc-Antoine Charpentier', 'Raymond Leppard', 'English Chamber Orchestra']                                              1
['Jesse Belvin']                                                                                                          1
['Richard Strauss', 'Julius Patzak', 'Margareta Kenney', 'Walter Berry', 'Wiener Philharmoniker', 'Clemens Krauss']       1
['Pyotr Ilyich Tchaikovsky', 'Philharmonia Orchestra', 'Paul Kletzki']                                                    1
['Red Camp']                                                                                                              1
Name: count, Length: 32006, dtype: int64

In [23]:
len(df['artists'].value_counts()[df['artists'].value_counts() > 1])

13074

In [24]:
df['artists'].value_counts()[df['artists'].value_counts() > 1]

artists
['Эрнест Хемингуэй']                                                                                           1211
['Эрих Мария Ремарк']                                                                                          1068
['Francisco Canaro']                                                                                            942
['Ignacio Corsini']                                                                                             628
['Frank Sinatra']                                                                                               603
                                                                                                               ...
['Giuseppe Verdi', 'Vittorio Gui', 'Caterina Mancini', 'Orchestra Sinfonica di Roma della RAI']                   2
['Claude Debussy', 'Heinz Rehfuss', 'Suzanne Danco', "L'Orchestre de la Suisse Romande", 'Ernest Ansermet']       2
['Sy Oliver']                                                                                                     2
['Tony Proteau & His Orchestra']                                                                                  2
['Wolfgang Amadeus Mozart', 'Anny Schlemm', 'Sir Georg Solti', 'Royal Philharmonic Orchestra']                    2
Name: count, Length: 13074, dtype: int64

In [25]:
df['name'].duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
170648     True
170649     True
170650     True
170651     True
170652     True
Name: name, Length: 170653, dtype: bool

In [26]:
df['name'].duplicated().sum()

np.int64(46299)